on:
  schedule:
    - cron: '0,2,5,10 10 * * *' # runs at 8:00pm, 8:02pm, 8:05pm, 8:10pm (AEST)
    - cron: '13 * * * *' # runs hourly thereafter at 13 past the hour
  push:
    branches:
      - master

name: Fetch and store

jobs:
  fetch:
    name: Fetch and store
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - name: Install packages
    timeout-minutes: 3
    run: |
        yarn
    - name: Scrape and generate data
      timeout-minutes: 3
      run: |
        node scrape.js
        node create-legacy-data.js
        node generate-csv.js
    - name: Push data
      run: |
          git config user.name jxeeno
          git config user.email ken+github@jxeeno.com
          git add . || exit 0
          git commit -m "auto(): update data" || exit 0
          git push || exit 0
